### ISSUE TITLE
Marking of Left and Right speaker outputs on SqueezeAMP PCB are swapped

### ISSUE THREAD

**Issue by CornelisJ** [philippe44/SqueezeAMP#2]
When playing a channel check test track on SqueezeAMP, I noticed that the markings of the left and right speaker outputs on the SqueezeAMP PCB are swapped. The left channel test signal came from the speaker connected to R+/R-, and the right channel test signal from the speaker connected to L+/L-.

This swap is confirmed by checking the speaker connections on the PCB against information in the datasheet of the TAS5780M DAC+ClassD amplifier. The TAS5780M datasheet states (section 9.4.3.1 on page 54):
By default, the TAS5780M device is configured to output the Right frame of an I2S input signal on the Channel A output and the Left frame on the Channel B output.
However on the SqueezeAMP PCB, SPK_OUTA+/- signals are routed to the speaker terminals marked L+/L- (i.e. via LC low pass filter), and the SPK_OUTB+/- signals are routed to speaker terminals marked R+/R-. So the L/R speaker markings on the PCB are not correct.

Workaround: When connecting speakers to SqueezeAMP, connect the Left speaker to the terminals marked R+/R-, and the Right speaker to the terminals marked L+/L-.

PS: Connection of Left and Right signals on the Line Out Jack are correct.

**Comment by philippe44** [comment]
Thanks for reporting that - I've fixed the silk in 3.12
