### ISSUE TITLE
Project not available anymore on PCBWay

### ISSUE THREAD

**Issue by acabrol** [philippe44/SqueezeAMP#4]
Hello everyone i try to buy the project on PCBWay but it doesn't seem to exist anymore.

Where can I buy a pre-built version or a DIY kit?

**Comment by philippe44** [comment]
I don't have spare boards anymore but I will probably do a next batch in the few coming months

**Comment by emlynmac** [comment]
I put the gerber files into pcbway and got 5 boards made up for the boost.
I'm awaiting arrival of the boards. If they're good and you want one, I can send you one.

**Comment by emlynmac** [comment]
@acabrol My boards arrived; they look good. Let me know if you'd like one (DM me)

**Comment by Muehsal** [comment]
Hi there,

I have ordered the normal version with the Gerber files (labeled 3.20 in the repro) and a modified bom & picknplace (also from the repro) without charger and spdif from PCBWay. The SqueezeAmps work perfectly out of the Box (after flashing). I have chosen the TAS5756 as it was much cheaper

Thank you very much Philippe for sharing the design!

One small note: the silk screen of the 3.20 Gerber states a version 3.11. The diptrace file, however, has a silk screen with 3.20.

**Comment by Muehsal** [comment]
![PXL_20230401_203255037](https://user-images.githubusercontent.com/36635631/229313274-96c35e91-0ef5-4224-baa7-1c7563a6158b.jpg)
![PXL_20230401_203223600](https://user-images.githubusercontent.com/36635631/229313277-67ad0373-8185-4386-a6e1-a2aeb6858983.jpg)

**Comment by philippe44** [comment]
Looks good!

**Comment by joffito** [comment]
If anybody got any board (populated / unpopulated) left, i'd happily buy one. cheers and thanks for sharing this great project :)

**Comment by philippe44** [comment]
I have plenty of PCBs

**Comment by joffito** [comment]
Sounds good :-) How to buy one / contact you? I think the DM message feature is not available in Github?

**Comment by philippe44** [comment]
Go on the Logitech media server forum, there is a thread on 3rd party HW about SqueezeAMP and you can contact me from there. These PCB cost nothing so it's just about putting one in an envelope

**Comment by acabrol** [comment]
> @acabrol My boards arrived; they look good. Let me know if you'd like one (DM me)

Can you post the updated link to PCBway?


I think i could insert the squeezeamp esp32 in this DIY kit: 
https://a.aliexpress.com/_EQdlhwn

**Comment by agdamsbo** [comment]
> Hi there,
> 
> I have ordered the normal version with the Gerber files (labeled 3.20 in the repro) and a modified bom & picknplace (also from the repro) without charger and spdif from PCBWay. The SqueezeAmps work perfectly out of the Box (after flashing). I have chosen the TAS5756 as it was much cheaper
> 
> Thank you very much Philippe for sharing the design!
> 
> One small note: the silk screen of the 3.20 Gerber states a version 3.11. The diptrace file, however, has a silk screen with 3.20.

@Muehsal Would you be willing to share your modified files? Ive had some troubles with PCBway, but would very much like to try my hands with a board just like the one I see you have ordered.

**Comment by Muehsal** [comment]
> > Hi there,
> > I have ordered the normal version with the Gerber files (labeled 3.20 in the repro) and a modified bom & picknplace (also from the repro) without charger and spdif from PCBWay. The SqueezeAmps work perfectly out of the Box (after flashing). I have chosen the TAS5756 as it was much cheaper
> > Thank you very much Philippe for sharing the design!
> > One small note: the silk screen of the 3.20 Gerber states a version 3.11. The diptrace file, however, has a silk screen with 3.20.
> 
> @Muehsal Would you be willing to share your modified files? Ive had some troubles with PCBway, but would very much like to try my hands with a board just like the one I see you have ordered.

I have sent you an email 🙂

**Comment by timotoots** [comment]
> > > Hi there,
> > > I have ordered the normal version with the Gerber files (labeled 3.20 in the repro) and a modified bom & picknplace (also from the repro) without charger and spdif from PCBWay. The SqueezeAmps work perfectly out of the Box (after flashing). I have chosen the TAS5756 as it was much cheaper
> > > Thank you very much Philippe for sharing the design!
> > > One small note: the silk screen of the 3.20 Gerber states a version 3.11. The diptrace file, however, has a silk screen with 3.20.
> > 
> > 
> > @Muehsal Would you be willing to share your modified files? Ive had some troubles with PCBway, but would very much like to try my hands with a board just like the one I see you have ordered.
> 
> I have sent you an email 🙂

I would also be interested in your version. Could you send me this as well? Thanks!

**Comment by emlynmac** [comment]
> I have plenty of PCBs

Do you still have any left? 
I have a workshop I'm going to run on SMD and I'd like to have a board to be able to stencil on.

**Comment by philippe44** [comment]
Yes I do
