### ISSUE TITLE
Cant Open dip dch

### ISSUE THREAD

**Issue by r1ckdu** [philippe44/SqueezeAMP#5]
I cannot open the files:
SqueezeAMP-3.20.dch
SqueezeAMP-3.20.dip

I was hoping i could check out the schematics a bit, is there something special i need to do to achieve this?

**Comment by philippe44** [comment]
You need to install diptrace (free)

**Comment by r1ckdu** [comment]
I have. It says the file is corrupted.

Mar 30, 2023 20:18:36 philippe44 ***@***.***>:

**Comment by r1ckdu** [comment]
Maybe drop that - i  think this was a stupid error of me not downloading the file correctly, i cloned the whole git and no errors anymore. Closed :)
