### ISSUE TITLE
Boot time + a bunch of functional questions

### ISSUE THREAD

**Issue by b0redng33k** [philippe44/SqueezeAMP#6]
I'm looking for options for an Airplay/Bluetooth receiver + MP3 player (from SD Card) with SPDIF (optical) output.

I've found this project along with https://github.com/sle118/squeezelite-esp32 and IIUC it seems to tick most boxes, however, I have a few more questions if you don't mind.

1) What is the boot time ?
2) Can it drive I2C + SPI (LCD) + I2S (or Optical SPDIF) all at once ?
3) Can it be used stand alone ? (i.e.: read MP3 from SD Card controlled via Web interface)
4) How is Bluetooth and Airplay arbitrated ? Let's say I connect to it with my phone over Bluetooth, then I send it audio from the computer via Airplay. Would it switch from Bluetooth to Airplay ? If I stop Airplay would it go back to Bluetooth or do I have to reconnect ?

Right now I'm using a RPi Zero W with Volumio but I'm not happy with boot times, it takes for ever to boot (a few minutes) because it reindexes the MP3s on the SD Card at every boot + sometimes it just crashes.

TIA

**Comment by philippe44** [comment]
It takes less than 10 seconds to boot
It can do i2s and one display using i2c or spi but data displayed is basic unless you use LMS
It does not do standalone 
BT and AirPlay are basically arbitrated. First come first served.
You can look at @feelfreelinux project for something more standalone

**Comment by b0redng33k** [comment]
Great thanks !
What should I be looking at on @feelfreelinux ? I found this https://github.com/feelfreelinux/cspot but I don't know if that's what you had in mind

**Comment by philippe44** [comment]
It's on the muvox-io repository on GitHub, named euphonium.
