### ISSUE TITLE
Please release the latest 3.x version as a release

### ISSUE THREAD

**Issue by ElektronikCZ** [philippe44/SqueezeAMP#8]
Im a dummy and i downloaded the 1.5 zip from releases and got it made by pcbway instead of the 3.x (facepalm). Making the latest version a "release" might be handy for other hasty people lol.

**Comment by philippe44** [comment]
I will - did you want just the PCB of the fully assembled? I have PCB and I'm preparing an new batch

**Comment by ElektronikCZ** [comment]
I wanted a bare PCB to hand assemble. I think the version 1.5 shouldnt be a big issue for me, but ill be more careful next time.

**Comment by philippe44** [comment]
There a few changes that matter and I have a few spares of 3.20. It’s just a matter of putting a stamp on an envelope if you want a couple.

Envoyé de mon iPhone

Le 17 août 2023 à 01:32, ElektronikCZ ***@***.***> a écrit :

﻿

I wanted a bare PCB to hand assemble. I think the version 1.5 shouldnt be a big issue for me, but ill be more careful next time.
